version: '3.8'

services:

  mysql:
    image: mysql:latest
    volumes:
      - ./configs/setups/mysql_setup.sql:/data/application/mysql_setup.sql
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
      MYSQL_USER: "luntaixia"
      MYSQL_PASSWORD: "luntaixia"
      MYSQL_DATABASE: "finlens"
    secrets:
      - mysql_root_password
    ports:
      - 3308:3306
    command:
      --init-file=/data/application/mysql_setup.sql
      --log-error-verbosity=1
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      #test: ["CMD", "whoami"]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    image: luntaixia/finlens-backend:latest
    environment:
      - ENV=prod
    volumes:
      - ./secrets.toml:/secrets.toml
    ports:
      - 8181:8181
    command:
      ./start.sh
    healthcheck:
      test: |
        python -c "import requests; r = requests.get('http://localhost:8181'); assert r.status_code == 200"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: luntaixia/finlens-frontend:latest
    environment:
      - SERVE_APP_HOST=backend
      - SERVE_APP_PORT=8181
    ports:
      - 8501:8501
    command:
      streamlit run app.py
    depends_on:
      - backend


secrets:
   mysql_root_password:
     file: ./configs/secrets/mysql_root_password.txt

volumes:
  mysql-volume:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nolock,rw,soft,nfsvers=4"
      device: ":${NFS_VOLUME_MYSQL}"