version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    volumes:
      - ./configs/setups/mysql_setup.sql:/data/application/mysql_setup.sql
      - mariadb-volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_USER: "root"
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/mariadb_root_password"
      MARIADB_USER: "luntaixia"
      MARIADB_PASSWORD: "luntaixia"
      MARIADB_DATABASE: "finlens"
    secrets:
      - mariadb_root_password
    ports:
      - 3309:3306
    command:
      --init-file=/data/application/mysql_setup.sql
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MARIADB_ROOT_PASSWORD']
      #test: ["CMD", "whoami"]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    image: luntaixia/finlens-backend:latest
    environment:
      - ENV=prod
    volumes:
      - ./secrets.toml:/secrets.toml
    ports:
      - 8182:8181
    command:
      ./start.sh
    healthcheck:
      test: |
        python -c "import requests; r = requests.get('http://localhost:8181'); assert r.status_code == 200"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: luntaixia/finlens-frontend:latest
    environment:
      - SERVE_APP_HOST=backend
      - SERVE_APP_PORT=8181
    ports:
      - 8502:8501
    command:
      streamlit run app.py
    depends_on:
      backend:
        condition: service_healthy


secrets:
   mariadb_root_password:
     file: configs/secrets/mysql_root_password.txt

volumes:
  mariadb-volume: