version: '3.8'

services:

  secret-store:
    image: vault:1.13.3
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "backend":{
            "file":{
                "path":"/vault/file"
            }
          },
          "listener":{
            "tcp":{
                "address":"0.0.0.0:8200",
                "tls_disable":1
            }
          },
          "default_lease_ttl":"168h",
          "max_lease_ttl":"0h",
          "ui":true,
          "log_level":"Debug"
        }
    ports:
      - 8200:8200
    volumes:
      - vault-volume:/vault/file:rw
    command: server

  obj-storage:
    image: quay.io/minio/minio:latest
    ports:
      - 9002:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_VOLUMES: /data
    volumes:
      - minio-volume:/data
    command: server --console-address ":9001" /data

  static-server:
    image: jdkelley/simple-http-server
    ports:
      - 8089:8080
      - 8088:8000
    volumes:
      - ./contents:/serve

volumes:
  vault-volume:
  minio-volume:
  