name: Sample Run
on:
  push:
    branches:
      - feat

jobs:
  update-frontend-image:
    runs-on: [self-hosted] # need self hosted runner as need connect to local servers

    steps:
      - uses: actions/checkout@v4

      - name: pull frontend image on prod machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          password: ${{ secrets.PROD_PASSWORD }}
          username: ${{ secrets.PROD_USERNAME }}
          port: ${{ secrets.PROD_PORT }}
          envs: IMAGE
          script: |
            echo "Login to $(hostname)"
            docker ps -a