name: Unit-Test-Build-on-Push-and-PR
on:
  push:
    branches:
      - main
    paths-ignore:
      - "configs/**"
      - "*gitignore"
      - "*dockerignore"
  pull_request:
    types: [opened, reopened]
    branches:
      - main
    paths-ignore:
      - "configs/**"
      - "*gitignore"
      - "*dockerignore"

jobs:
  limit-changes-backend:
    # finds out which files to watch for unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: file_watch_list_backend
        with:
          filters: |
            code:
              - 'backend/**'
    outputs:
      changelist: ${{ steps.file_watch_list_backend.outputs.code }}

  unit-test:
    runs-on: ubuntu-latest
    needs: limit-changes-backend
    if: ${{ needs.limit-changes-backend.outputs.changelist == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install python library
        working-directory: backend
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: unit testing
        working-directory: backend
        env:
          ENV: dev
        run: |
          python -m pytest -s .

