name: Unit-Test-Build-on-Push-and-PR
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "configs/**"
      - "*gitignore"
      - "*dockerignore"

jobs:
  limit-changes-backend:
    # finds out which files to watch for unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: file_watch_list_backend
        with:
          filters: |
            code:
              - 'backend/**'
    outputs:
      changelist: ${{ steps.file_watch_list_backend.outputs.code }}

  unit-test:
    runs-on: ubuntu-latest
    needs: limit-changes-backend
    if: ${{ (needs.limit-changes-backend.outputs.changelist == 'true') && !contains(github.ref, 'refs/tags/')}}
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        working-directory: backend
        with:
          python-version-file: "pyproject.toml"
      
      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: install the project
        working-directory: backend
        run: uv sync --locked --all-extras --dev

      - name: unit testing
        working-directory: backend
        env:
          ENV: dev
        run: |
          uv run pytest -s .

